using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PickUpSystem : MonoBehaviour
{
    [SerializeField]
    private InventorySO inventoryData;

    private void OnTriggerEnter(Collider collision)
    {

        
        Item item = collision.GetComponent<Item>();
        if (item != null )
        {
            Debug.Log("dd");
            int reminder = inventoryData.AddItem(item.InventoryItem, item.Quantity);
            if (reminder == 0)
            {
                item.DestroyItem();
            }           
            else
            {
                item.Quantity = reminder;

            }
        }
    }

}
